name: Build KivyMD APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies and Buildozer
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip openjdk-11-jdk zip unzip
        pip install --upgrade pip
        pip install buildozer cython
        buildozer android clean

    - name: Build APK
      run: |
        buildozer -v android debug
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: bin/*.apk
