name: Build
on:
  push:

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      actions: read
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1.0.0
        id: buildozer
        with:
          workdir: .
          buildozer_version: stable
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
